# Generated by Django 5.1.2 on 2024-11-27 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_user_role_course_student_tutor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='image',
        ),
    ]
