# Generated by Django 5.1.2 on 2024-12-02 19:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0004_remove_course_user_course_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability', models.JSONField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('courses', models.ManyToManyField(to='tutorials.course')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
