# Generated by Django 5.1.2 on 2024-12-04 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0005_requestsession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestsession',
            name='courses',
        ),
        migrations.AddField(
            model_name='requestsession',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorials.course'),
        ),
        migrations.RemoveField(
            model_name='requestsession',
            name='user',
        ),
        migrations.AddField(
            model_name='requestsession',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
