# Generated by Django 5.1.2 on 2024-12-05 14:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0006_remove_requestsession_courses_requestsession_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestsession',
            name='status',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='requestsession',
            name='tutor',
            field=models.ManyToManyField(null=True, related_name='request_sessions_tutor', to=settings.AUTH_USER_MODEL),
        ),
    ]
