# Generated by Django 5.1.2 on 2024-12-08 21:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutorials", "0007_requestsession_status_requestsession_tutor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="requestsession",
            name="user",
        ),
        migrations.AddField(
            model_name="requestsession",
            name="student",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="request_sessions_student",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RemoveField(
            model_name="requestsession",
            name="tutor",
        ),
        migrations.AddField(
            model_name="requestsession",
            name="tutor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="request_sessions_tutor",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
