# Generated by Django 5.1.2 on 2024-12-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "tutorials",
            "0008_remove_requestsession_user_requestsession_student_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="requestsession",
            name="status",
            field=models.BooleanField(default=None, null=True),
        ),
    ]
