# Generated by Django 5.1.2 on 2024-12-09 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutorials", "0009_alter_requestsession_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requestsession",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
