# Generated by Django 5.1.2 on 2024-12-10 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0011_invoices'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestsession',
            name='fortnightly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requestsession',
            name='venue',
            field=models.CharField(default='online', max_length=25),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='payment_date',
            field=models.DateField(null=True),
        ),
    ]
