# Generated by Django 5.1.2 on 2024-12-11 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0012_requestsession_fortnightly_requestsession_venue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
